from pathlib import Path

p=Path('src/import/emblemOcrRefinement.ts')
s=p.read_text()
old="function ambiguousTierGlyph(words:readonly Word[],currentTier:QualityTier):{tierWord:Word;glyphWord:Word}|undefined{if(currentTier!==1)return undefined;for(const tierWord of words.filter(w=>ocrSimilarity(w.text,'TIER')>=.62)){const tierRight=tierWord.left+tierWord.width,tierY=tierWord.top+tierWord.height/2;for(const glyphWord of words){const token=glyphWord.text.toUpperCase().replace(/[^A-Z0-9\\]|]/g,''),confused=token.replace(/[1L|]/g,'I').replace(/]/g,'I'),glyphY=glyphWord.top+glyphWord.height/2,yTolerance=Math.max(tierWord.height,glyphWord.height)*.7,rightGap=glyphWord.left-tierRight,maxGap=Math.max(12,tierWord.height*1.5);if(confused==='I'&&glyphWord.confidence<TIER_GLYPH_RETRY_CONFIDENCE_CEILING&&Math.abs(glyphY-tierY)<=yTolerance&&rightGap>=-2&&rightGap<=maxGap)return{tierWord,glyphWord};}}return undefined;}"
new="function ambiguousTierGlyphEvidence(words:readonly {text:string;confidence:number;x:number;y:number}[]|undefined,currentTier:QualityTier):boolean{if(currentTier!==1||!words?.length)return false;for(const tierWord of words.filter(w=>ocrSimilarity(w.text,'TIER')>=.62)){for(const glyphWord of words){const token=glyphWord.text.toUpperCase().replace(/[^A-Z0-9\\]|]/g,''),confused=token.replace(/[1L|]/g,'I').replace(/]/g,'I'),dx=glyphWord.x-tierWord.x,dy=Math.abs(glyphWord.y-tierWord.y);if(confused==='I'&&glyphWord.confidence<TIER_GLYPH_RETRY_CONFIDENCE_CEILING&&dx>0&&dx<=40&&dy<=6)return true;}}return false;}\nfunction tierAnchorWord(words:readonly Word[]):Word|undefined{return words.filter(w=>ocrSimilarity(w.text,'TIER')>=.62).sort((a,b)=>b.confidence-a.confidence)[0];}"
assert old in s, 'word-geometry helper not found'
s=s.replace(old,new,1)
old_call="const tier=bestTierLine(ls),tierConfidence=combined(tier.match.score,tier.line?.words??words),ambiguousGlyph=ambiguousTierGlyph(words,raw.banners[role].emblems[i]!.qualityTier);if(tier.direct&&tierConfidence>confidenceFor(raw,qp)){raw.banners[role].emblems[i]!.qualityTier=tier.match.value;replaceConfidence(raw,qp,Math.min(.84,tierConfidence));d.normalizedTier=tier.match.value;d.tierMatchScore=tier.match.score;}if(!budget.exhausted&&ambiguousGlyph&&shouldRetryTier(confidenceFor(raw,qp))){const {tierWord,glyphWord}=ambiguousGlyph,localPadX=Math.max(2,tierWord.height*.3),localPadY=Math.max(2,tierWord.height*.45),localLeft=Math.max(0,tierWord.left-localPadX),localTop=Math.max(0,Math.min(tierWord.top,glyphWord.top)-localPadY),localRight=Math.min(emblemCanvas.width,Math.max(tierWord.left+tierWord.width,glyphWord.left+glyphWord.width)+Math.max(4,tierWord.height*1.1)),localBottom=Math.min(emblemCanvas.height,Math.max(tierWord.top+tierWord.height,glyphWord.top+glyphWord.height)+localPadY),sourceLeft=Math.max(0,Math.floor(rr.left)),sourceTop=Math.max(0,Math.floor(rr.top)),tightLeft=Math.max(0,sourceLeft+localLeft),tightTop=Math.max(0,sourceTop+localTop),tightRight=Math.min(src.naturalWidth,sourceLeft+localRight),tightBottom=Math.min(src.naturalHeight,sourceTop+localBottom),tightWidth=tightRight-tightLeft,tightHeight=tightBottom-tightTop;"
new_call="const tier=bestTierLine(ls),tierConfidence=combined(tier.match.score,tier.line?.words??words),ambiguousGlyph=ambiguousTierGlyphEvidence(d.words,raw.banners[role].emblems[i]!.qualityTier),tierWord=ambiguousGlyph?tierAnchorWord(words):undefined;if(tier.direct&&tierConfidence>confidenceFor(raw,qp)){raw.banners[role].emblems[i]!.qualityTier=tier.match.value;replaceConfidence(raw,qp,Math.min(.84,tierConfidence));d.normalizedTier=tier.match.value;d.tierMatchScore=tier.match.score;}if(!budget.exhausted&&tierWord&&shouldRetryTier(confidenceFor(raw,qp))){const localPadX=Math.max(2,tierWord.height*.3),localPadY=Math.max(2,tierWord.height*.55),localLeft=Math.max(0,tierWord.left-localPadX),localTop=Math.max(0,tierWord.top-localPadY),localRight=Math.min(emblemCanvas.width,tierWord.left+tierWord.width+Math.max(10,tierWord.height*2.4)),localBottom=Math.min(emblemCanvas.height,tierWord.top+tierWord.height+localPadY),sourceLeft=Math.max(0,Math.floor(rr.left)),sourceTop=Math.max(0,Math.floor(rr.top)),tightLeft=Math.max(0,sourceLeft+localLeft),tightTop=Math.max(0,sourceTop+localTop),tightRight=Math.min(src.naturalWidth,sourceLeft+localRight),tightBottom=Math.min(src.naturalHeight,sourceTop+localBottom),tightWidth=tightRight-tightLeft,tightHeight=tightBottom-tightTop;"
assert old_call in s, 'old tight-tier block anchor not found'
s=s.replace(old_call,new_call,1)
p.write_text(s)

t=Path('tests/p52-tier-glyph-retry.test.mjs')
ts=t.read_text()
start=ts.index("test('ambiguous direct Tier-I glyph retry")
# Keep imports, replace the single test block wholesale.
prefix=ts[:start]
replacement="""test('ambiguous Tier-I glyph retry uses initial direct glyph evidence and a bounded TIER-anchor crop',()=>{\n  assert.match(source,/const TIER_GLYPH_RETRY_CONFIDENCE_CEILING=60/);\n  assert.match(source,/currentTier!==1\\|\\|!words\\?\\.length/);\n  assert.match(source,/words\\.filter\\(w=>ocrSimilarity\\(w\\.text,'TIER'\\)>=\\.62\\)/);\n  assert.match(source,/glyphWord\\.confidence<TIER_GLYPH_RETRY_CONFIDENCE_CEILING&&dx>0&&dx<=40&&dy<=6/);\n  assert.match(source,/ambiguousTierGlyphEvidence\\(d\\.words,raw\\.banners\\[role\\]\\.emblems\\[i\\]!\\.qualityTier\\)/);\n  assert.match(source,/tierAnchorWord\\(words\\)/);\n  assert.match(source,/tierWord\\.left\\+tierWord\\.width\\+Math\\.max\\(10,tierWord\\.height\\*2\\.4\\)/);\n  assert.match(source,/tightRight=Math\\.min\\(src\\.naturalWidth,sourceLeft\\+localRight\\)/);\n  assert.match(source,/tightBottom=Math\\.min\\(src\\.naturalHeight,sourceTop\\+localBottom\\)/);\n  assert.match(source,/if\\(tightWidth>0&&tightHeight>0\\)/);\n  assert.match(source,/tightTierCanvas=otsuCanvas\\(canvas\\(src,tightTierStrip\\)\\)/);\n  assert.match(source,/`tier:\\$\\{role\\}:\\$\\{i\\+1\\}:glyph`/);\n  assert.match(source,/tightTier\\.direct&&tightTierConfidence>tierConfidence/);\n  assert.match(source,/Math\\.min\\(\\.84,tightTierConfidence\\)/);\n  assert.equal((source.match(/`tier:\\$\\{role\\}:\\$\\{i\\+1\\}:glyph`/g)??[]).length,1);\n  assert.doesNotMatch(source,/percentage.*tier|tier.*percentage/i);\n});\n"""
t.write_text(prefix+replacement)
