import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';
import {ACTION_BY_ID,cloneAction} from '../docs/js/data/actionCatalog.js';import {defaultBoard} from '../docs/js/data/defaultState.js';import {enumerateEngineOperation} from '../docs/js/engine/compactTransitions.js';import {boardToEngineState} from '../docs/js/engine/stateEncoding.js';import {evaluateM5GGate,rankingsEqual,isM5GCaseArtifactPath} from '../scripts/m5g-benchmark-lib.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../benchmarks/m5g-target-robustness-fixtures.json',import.meta.url),'utf8')),holdouts=JSON.parse(fs.readFileSync(new URL('../benchmarks/m5d-holdout-fixtures.json',import.meta.url),'utf8')).fixtures;const action=id=>cloneAction(ACTION_BY_ID.get(id));
function replay(id){let e=boardToEngineState(defaultBoard);if(id==='canonical-default')return e;const f=holdouts.find(x=>x.name===id);for(const m of f.mutations)e=enumerateEngineOperation(e,m.role,action(m.operationId),true)[m.outcomeIndex].nextState;return e;}
test('M5G corpus is exactly frozen 9 x 3 matrix',()=>{assert.equal(manifest.M5G_BASE_SHA,'a138a7b968350e97261c2631c8298521d07b72d4');assert.deepEqual(manifest.thresholds,[50000,55000,60000]);assert.equal(manifest.fixtures.length,9);const ids=manifest.fixtures.flatMap(f=>manifest.thresholds.map(t=>`${f.id}-${t}`));assert.equal(ids.length,27);assert.equal(new Set(ids).size,27);assert.deepEqual(manifest.fixtures[0].menu,['green-stat-all','red-quality-all','blue-trait-all']);assert.deepEqual(manifest.fixtures.slice(1).map(x=>x.id),holdouts.map(x=>x.name));assert.deepEqual(manifest.fixtures.slice(1).map(x=>x.menu),holdouts.map(x=>x.menu));});
test('all frozen fixture boards replay to frozen BoardStateIDs and operations exist',()=>{for(const f of manifest.fixtures){assert.equal(String(replay(f.id).id),f.boardStateId);for(const id of f.menu)assert.ok(ACTION_BY_ID.has(id),`${f.id} missing ${id}`);}});
test('M5G policies and production horizon are frozen',()=>{assert.equal(manifest.productionHorizon,2);assert.equal(manifest.experimentHorizon,3);assert.deepEqual(manifest.oracle,{continuationFidelity:'current',actionWidening:'none',timeoutMs:600000});assert.deepEqual(manifest.candidate.continuationSchedule,[4,2,1]);assert.deepEqual(manifest.candidate.wideningSchedule,[12,8,4]);assert.equal(manifest.candidate.timeoutMs,60000);});
test('aggregation accepts only frozen case artifact filenames',()=>{assert.ok(isM5GCaseArtifactPath('m5g-canonical-default-50000.json'));assert.ok(isM5GCaseArtifactPath('/tmp/results/m5g-holdout-08-60000.json'));for(const file of ['m5g-plan.json','m5g-sentinel.json','m5g-preflight.json','m5g-holdout-09-50000.json','m5g-holdout-01-57500.json','other.json'])assert.ok(!isM5GCaseArtifactPath(file),file);});
const row=(key,u)=>({key,utility:u,expectedScore:u*1000});function run(key='board_action|x|core',u=0.8,runtimeMs=1000,rss=1e9){return {status:'completed',horizon:3,fidelityId:'current',wideningId:'none',runtimeMs,memory:{maxRssBytes:rss},recommendationKey:key,utility:u,ranking:[row(key,u),row('board_action|y|mid',u-.005),row('menu_reroll',.4),row('stop',.2)],futureOperationIds:Array.from({length:20},(_,i)=>`op${i}`)};}function report(){const cases=[];for(const f of manifest.fixtures)for(const targetScore of manifest.thresholds){const oracle=run(),candidate={...run(),fidelityId:'aggressive',wideningId:'wide'};cases.push({caseId:`${f.id}-${targetScore}`,fixtureId:f.id,targetScore,productionIsolationPassed:true,oracle,candidate,comparison:{topActionAgreement:true,oracleBestKey:oracle.recommendationKey,candidateBestKey:candidate.recommendationKey,oracleTopTwoGap:.005,oracleRegret:0,kendallTau:1,top3Overlap:3,oracleType:'board_action',candidateType:'board_action',oracleFamily:'other',candidateFamily:'other',stopMenuReversal:false,runtimeRatio:1}});}return {preflightPassed:true,sentinelPassed:true,fixtureIntegrityPassed:true,productionHorizon:2,cases};}
test('gate passes 27/27 exact agreement',()=>assert.equal(evaluateM5GGate(report()).outcome,'A'));
test('gate permits one frozen near-tie board-action disagreement only',()=>{const r=report(),c=r.cases[0];c.candidate.recommendationKey='board_action|y|mid';c.comparison={...c.comparison,topActionAgreement:false,candidateBestKey:c.candidate.recommendationKey,oracleTopTwoGap:.01,oracleRegret:.0025};assert.equal(evaluateM5GGate(r).outcome,'A');});
test('gate rejects two disagreements, stop/menu, large gap, large regret and mean regret',()=>{for(const mutate of [r=>{for(const c of r.cases.slice(0,2))c.comparison={...c.comparison,topActionAgreement:false,oracleRegret:.001};},r=>{r.cases[0].comparison={...r.cases[0].comparison,topActionAgreement:false,candidateType:'menu_reroll',stopMenuReversal:true,oracleRegret:0};},r=>{r.cases[0].comparison={...r.cases[0].comparison,topActionAgreement:false,oracleTopTwoGap:.0101,oracleRegret:0};},r=>{r.cases[0].comparison={...r.cases[0].comparison,topActionAgreement:false,oracleRegret:.0026};},r=>{for(const c of r.cases)c.comparison.oracleRegret=.00051;}]){const r=report();mutate(r);assert.equal(evaluateM5GGate(r).outcome,'B');}});
test('gate rejects candidate/oracle timeout, memory, missing case, isolation and monotonicity failures',()=>{for(const mutate of [r=>{r.cases[0].candidate.runtimeMs=60000;},r=>{r.cases[0].oracle.status='timeout';},r=>{r.cases[0].oracle.memory.maxRssBytes=6*1024**3;},r=>{r.cases.pop();},r=>{r.cases[0].productionIsolationPassed=false;},r=>{const g=r.cases.filter(c=>c.fixtureId==='canonical-default');g[1].oracle.ranking[0].utility=g[0].oracle.ranking[0].utility+.01;}]){const r=report();mutate(r);assert.equal(evaluateM5GGate(r).outcome,'B');}});
test('ranked-table equality is complete and numerical',()=>{const a=[row('a',1),row('b',.5)];assert.ok(rankingsEqual(a,structuredClone(a)));assert.ok(!rankingsEqual(a,[row('b',1),row('a',.5)]));assert.ok(!rankingsEqual(a,[row('a',1.1),row('b',.5)]));});
