import type { DataBundle, QualityTier, Role, StatName, TraitName } from '../domain/types.js';
import { BOARD_LAYOUTS, LEGAL_STAT_POOLS } from '../domain/rules.js';
import type { LocalScreenshotOcrMetrics } from './localScreenshotOcr.js';
import { matchActionText, matchStatLines, matchTierText, matchTraitText, ocrSimilarity } from './ocrDomainMatch.js';
import type { RawScreenshotImport, ScreenshotFieldConfidence } from './screenshotImport.js';

const ROLES:readonly Role[]=['core','mid','support'];
const TRAITS:readonly TraitName[]=['Fractal','Friendly','Vampiric','Unique','Benevolent'];
interface Word{text:string;confidence:number;left:number;top:number;width:number;height:number;lineKey:string;}
interface Worker{recognize(image:HTMLCanvasElement,options?:Record<string,unknown>,output?:Record<string,boolean>):Promise<{data:{tsv?:string}}>;setParameters(params:Record<string,unknown>):Promise<unknown>;}
interface Tess{createWorker(language?:string):Promise<Worker>;}
interface Rect{left:number;top:number;width:number;height:number;}
interface Line{words:Word[];text:string;y:number;x:number;}
let workerPromise:Promise<Worker>|undefined;

function parse(tsv?:string):Word[]{if(!tsv)return[];const out:Word[]=[];for(const row of tsv.split(/\r?\n/).slice(1)){const c=row.split('\t');if(c.length<12||c[0]!=='5')continue;const text=c.slice(11).join('\t').trim();if(text)out.push({text,confidence:Number(c[10])||0,left:Number(c[6])||0,top:Number(c[7])||0,width:Number(c[8])||0,height:Number(c[9])||0,lineKey:`${c[1]}:${c[2]}:${c[3]}:${c[4]}`});}return out;}
async function worker():Promise<Worker>{workerPromise??=(async()=>{const T=(window as unknown as {Tesseract?:Tess}).Tesseract;if(!T)throw new Error('Local OCR runtime is unavailable for screenshot refinement.');const w=await T.createWorker('eng');await w.setParameters({tessedit_pageseg_mode:'6'});return w;})();return workerPromise;}
async function image(file:File):Promise<HTMLImageElement>{return await new Promise((ok,no)=>{const i=new Image(),u=URL.createObjectURL(file);i.onload=()=>{URL.revokeObjectURL(u);ok(i);};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error('Could not decode screenshot for refinement.'));};i.src=u;});}
function canvas(i:HTMLImageElement,r:Rect):HTMLCanvasElement{const left=Math.max(0,Math.floor(r.left)),top=Math.max(0,Math.floor(r.top)),right=Math.min(i.naturalWidth,Math.ceil(r.left+r.width)),bottom=Math.min(i.naturalHeight,Math.ceil(r.top+r.height)),c=document.createElement('canvas');c.width=Math.max(1,right-left);c.height=Math.max(1,bottom-top);const x=c.getContext('2d');if(!x)throw new Error('Canvas unavailable.');x.drawImage(i,left,top,c.width,c.height,0,0,c.width,c.height);return c;}
function confidenceFor(raw:RawScreenshotImport,path:string):number{return raw.fieldConfidence?.find(x=>x.path===path)?.confidence??0;}
function setConfidence(raw:RawScreenshotImport,path:string,confidence:number):void{raw.fieldConfidence??=[];const old=raw.fieldConfidence.find(x=>x.path===path);if(old)old.confidence=Math.max(old.confidence,confidence);else raw.fieldConfidence.push({path,confidence} satisfies ScreenshotFieldConfidence);}
function replaceConfidence(raw:RawScreenshotImport,path:string,confidence:number):void{raw.fieldConfidence??=[];const old=raw.fieldConfidence.find(x=>x.path===path);if(old)old.confidence=Math.max(0,Math.min(1,confidence));else raw.fieldConfidence.push({path,confidence:Math.max(0,Math.min(1,confidence))} satisfies ScreenshotFieldConfidence);}
function extractionToSource(r:Rect,m:LocalScreenshotOcrMetrics):Rect{const c=m.diagnostic.sourceCrop,sx=c.width/m.extractionWidth,sy=c.height/m.extractionHeight;return{left:c.left+r.left*sx,top:c.top+r.top*sy,width:r.width*sx,height:r.height*sy};}
function orderedText(ws:readonly Word[]):string{return[...ws].sort((a,b)=>a.top-b.top||a.left-b.left).map(w=>w.text).join(' ');}
function ocrConfidence(ws:readonly Word[]):number{return ws.length?ws.reduce((sum,w)=>sum+w.confidence,0)/ws.length/100:0;}
function combined(match:number,ws:readonly Word[]):number{return Math.max(0,Math.min(.99,match*.82+ocrConfidence(ws)*.18));}
function lines(ws:readonly Word[]):Line[]{const grouped=new Map<string,Word[]>();for(const w of ws){const row=grouped.get(w.lineKey)??[];row.push(w);grouped.set(w.lineKey,row);}return[...grouped.values()].map(words=>{const sorted=[...words].sort((a,b)=>a.left-b.left);return{words:sorted,text:sorted.map(w=>w.text).join(' '),y:sorted.reduce((s,w)=>s+w.top+w.height/2,0)/sorted.length,x:sorted.reduce((s,w)=>s+w.left+w.width/2,0)/sorted.length};}).sort((a,b)=>a.y-b.y);}
function phrases(s:string,maxWords=3):string[]{const t=s.toUpperCase().match(/[A-Z0-9_-]+/g)??[],out=[...t];for(let n=2;n<=Math.min(maxWords,t.length);n++)for(let i=0;i<=t.length-n;i++)out.push(t.slice(i,i+n).join(' '));return out;}
function teamMatch(s:string,role:Role,data:DataBundle):{team:string;score:number}{let best={team:data.players.find(p=>p.role===role)?.team??'',score:0};const ps=phrases(s,3);for(const p of data.players.filter(x=>x.role===role)){const names=[p.name,...p.attachedPlayers],scores=names.map(name=>Math.max(0,...ps.map(x=>ocrSimilarity(x,name)))).sort((a,b)=>b-a),strong=scores.filter(x=>x>=.62),score=strong.length>=2?Math.min(.99,(strong[0]!+strong[1]!)/2):scores[0]??0;if(score>best.score)best={team:p.team,score};}return best;}
function directTier(line:Line):{value:QualityTier;score:number}|undefined{const cleaned=line.words.map(w=>w.text.replace(/[“”'`]/g,'').toUpperCase()),bonus=cleaned.map(x=>x.match(/^\+?(10|30|60|100|150)%$/)?.[1]).find(Boolean),bonusTier:Record<string,QualityTier>={'10':1,'30':2,'60':3,'100':4,'150':5};if(bonus)return{value:bonusTier[bonus]!,score:.99};const tierIndex=line.words.findIndex(w=>ocrSimilarity(w.text,'TIER')>=.62);if(tierIndex>=0){for(const token of cleaned.slice(tierIndex+1,tierIndex+3)){const roman=token.match(/^(I|II|III|IV|V)$/)?.[1];if(roman)return{value:({I:1,II:2,III:3,IV:4,V:5} as Record<string,QualityTier>)[roman]!,score:.97};}}return undefined;}
function bestTierLine(ls:readonly Line[]):{match:{value:QualityTier;score:number};line?:Line;direct:boolean}{let best:{match:{value:QualityTier;score:number};line?:Line;direct:boolean}={match:{value:1,score:.2},direct:false};for(const line of ls){const exact=directTier(line);if(exact&&exact.score>best.match.score)best={match:exact,line,direct:true};else if(!best.direct){const match=matchTierText(line.text),hasTier=line.words.some(w=>ocrSimilarity(w.text,'TIER')>=.62),score=Math.min(.85,match.score+(hasTier ? .08 : 0));if(score>best.match.score)best={match:{value:match.value,score},line,direct:false};}}return best;}
function bestTraitLine(ls:readonly Line[]):{match:{value:TraitName;score:number};line?:Line}{let best:{match:{value:TraitName;score:number};line?:Line}={match:{value:'Fractal',score:0}};for(const line of ls){const match=matchTraitText(line.text),score=Math.min(.99,match.score+(TRAITS.some(t=>line.text.toUpperCase().includes(t.toUpperCase())) ? .08 : 0));if(score>best.match.score)best={match:{value:match.value,score},line};}return best;}
function actionWordScore(s:string):number{return Math.max(...['REROLL','RANDOMLY','INCREASE','QUALITY','TRAIT','STAT','FIRST','LAST','RED','BLUE','GREEN','EMBLEM','EMBLEMS'].map(x=>ocrSimilarity(s,x)));}
function cluster3(words:readonly Word[]):Word[][]|undefined{const candidates=words.filter(w=>actionWordScore(w.text)>=.6);if(candidates.length<6)return undefined;let centers=[...candidates].sort((a,b)=>(a.left+a.width/2)-(b.left+b.width/2));let c=[centers[Math.floor(centers.length*.15)]!,centers[Math.floor(centers.length*.5)]!,centers[Math.floor(centers.length*.85)]!].map(w=>w.left+w.width/2);let groups:Word[][]=[[],[],[]];for(let iter=0;iter<10;iter++){groups=[[],[],[]];for(const w of candidates){const x=w.left+w.width/2;let k=0;if(Math.abs(x-c[1]!)<Math.abs(x-c[k]!))k=1;if(Math.abs(x-c[2]!)<Math.abs(x-c[k]!))k=2;groups[k]!.push(w);}if(groups.some(g=>g.length<2))return undefined;c=groups.map(g=>g.reduce((s,w)=>s+w.left+w.width/2,0)/g.length);}
return groups.map(g=>[...g].sort((a,b)=>a.top-b.top||a.left-b.left)).sort((a,b)=>a.reduce((s,w)=>s+w.left+w.width/2,0)/a.length-b.reduce((s,w)=>s+w.left+w.width/2,0)/b.length);}
function parseTokens(s:string):number|undefined{const m=s.match(/ROLL\s*TOKENS?\s*[:\-]?\s*(\d+)/i)??s.match(/TOKENS?\s*[:\-]?\s*(\d+)/i);return m?Number(m[1]):undefined;}

export interface ScreenshotRefinementResult{result:RawScreenshotImport;elapsedMs:number;retries:number;}

/** Retry only unresolved structured fields from native-resolution regions derived from observed geometry. */
export async function refineUncertainScreenshotFields(file:File,data:DataBundle,raw:RawScreenshotImport,metrics:LocalScreenshotOcrMetrics):Promise<ScreenshotRefinementResult>{
  const started=performance.now(),src=await image(file),w=await worker(),layout=BOARD_LAYOUTS[raw.layoutId];let retries=0,emblemRetries=0,teamRetries=0,footerRetries=0;
  const diagnostics=new Map(metrics.diagnostic.emblems.map(e=>[`${e.role}:${e.rowIndex}`,e] as const));
  for(const role of ROLES){for(let i=0;i<layout.roles[role].length;i++){
    const sp=`banners.${role}.emblems.${i}.stat`,qp=`banners.${role}.emblems.${i}.qualityTier`,tp=`banners.${role}.emblems.${i}.trait`,d=diagnostics.get(`${role}:${i}`);if(!d)continue;
    if(confidenceFor(raw,sp)>=.9&&confidenceFor(raw,qp)>=.9&&confidenceFor(raw,tp)>=.9)continue;
    const rr=extractionToSource({left:Math.max(0,d.roi.left-d.roi.width*.05),top:Math.max(0,d.roi.top-d.roi.height*.08),width:d.roi.width*1.08,height:d.roi.height*1.16},metrics),rec=await w.recognize(canvas(src,rr),{tessedit_pageseg_mode:'6'},{tsv:true}),words=parse(rec.data.tsv),ls=lines(words);retries++;emblemRetries++;
    if(confidenceFor(raw,sp)<.9){const sm=matchStatLines(ls.map(line=>line.text),LEGAL_STAT_POOLS[layout.roles[role][i]!.color]),statWords=sm.lineIndices.flatMap(index=>ls[index]?.words??[]),sc=combined(sm.score,statWords.length?statWords:words);if(sm.score>=.92&&sc>=.9&&sc>confidenceFor(raw,sp)){raw.banners[role].emblems[i]!.stat=sm.value;setConfidence(raw,sp,sc);d.normalizedStat=sm.value;d.statMatchScore=sm.score;}}
    if(confidenceFor(raw,sp)<.9){const base=extractionToSource(d.roi,metrics),statStrip={left:base.left,top:base.top,width:base.width,height:base.height*.38},statRec=await w.recognize(canvas(src,statStrip),{tessedit_pageseg_mode:'7'},{tsv:true}),statRetryWords=parse(statRec.data.tsv),statRetryLines=lines(statRetryWords),sm=matchStatLines(statRetryLines.map(line=>line.text),LEGAL_STAT_POOLS[layout.roles[role][i]!.color]),evidenceWords=sm.lineIndices.flatMap(index=>statRetryLines[index]?.words??[]).filter(word=>!/^\+?\d+%$/.test(word.text.trim())),sc=combined(sm.score,evidenceWords);retries++;emblemRetries++;if(sm.score>=.92&&sc>=.9&&sc>confidenceFor(raw,sp)){raw.banners[role].emblems[i]!.stat=sm.value;setConfidence(raw,sp,sc);d.normalizedStat=sm.value;d.statMatchScore=sm.score;}}
    const tier=bestTierLine(ls),qc=combined(tier.match.score,tier.line?.words??words);if(tier.direct&&tier.match.score>=.72&&qc>confidenceFor(raw,qp)){raw.banners[role].emblems[i]!.qualityTier=tier.match.value;setConfidence(raw,qp,qc);d.normalizedTier=tier.match.value;d.tierMatchScore=tier.match.score;}else if(!tier.direct){const base=extractionToSource(d.roi,metrics),strip={left:base.left+base.width*.02,top:base.top+base.height*.30,width:base.width*.96,height:base.height*.38},tierRec=await w.recognize(canvas(src,strip),{tessedit_pageseg_mode:'7'},{tsv:true}),tierWords=parse(tierRec.data.tsv),tierLines=lines(tierWords),retryTier=bestTierLine(tierLines);retries++;emblemRetries++;if(retryTier.direct){const retryConfidence=combined(retryTier.match.score,retryTier.line?.words??tierWords);raw.banners[role].emblems[i]!.qualityTier=retryTier.match.value;replaceConfidence(raw,qp,retryConfidence);d.normalizedTier=retryTier.match.value;d.tierMatchScore=retryTier.match.score;}else replaceConfidence(raw,qp,Math.min(confidenceFor(raw,qp),.75));}
    const trait=bestTraitLine(ls),tc=combined(trait.match.score,trait.line?.words??words);if(trait.match.score>=.62&&tc>confidenceFor(raw,tp)){raw.banners[role].emblems[i]!.trait=trait.match.value;setConfidence(raw,tp,tc);d.normalizedTrait=trait.match.value;d.traitMatchScore=trait.match.score;}
    d.finalConfidence=Math.min(confidenceFor(raw,sp),confidenceFor(raw,qp),confidenceFor(raw,tp));d.reviewRequired=d.finalConfidence<.9;
  }}

  const rows=metrics.diagnostic.globalRows,pitch=rows.length>1?rows.slice(1).map((y,i)=>y-rows[i]!).sort((a,b)=>a-b)[Math.floor((rows.length-1)/2)]!:Math.max(55,metrics.extractionHeight*.08),first=rows[0]??metrics.extractionHeight*.12;
  for(const role of ROLES){const path=`banners.${role}.selectedTeam`;if(confidenceFor(raw,path)>=.9)continue;const band=metrics.diagnostic.columnBands[role],bw=band.right-band.left,rect=extractionToSource({left:Math.max(0,band.left-bw*.08),top:0,width:bw*.55,height:Math.min(metrics.extractionHeight,first+pitch*.75)},metrics),rec=await w.recognize(canvas(src,rect),{tessedit_pageseg_mode:'6'},{tsv:true}),words=parse(rec.data.tsv),s=orderedText(words),match=teamMatch(s,role,data),confidence=combined(match.score,words);retries++;teamRetries++;metrics.diagnostic.teamEvidence[role]={rawText:s,normalizedTeam:match.team,matchScore:match.score};if(match.score>=.62&&confidence>confidenceFor(raw,path)){raw.banners[role].selectedTeam=match.team;setConfidence(raw,path,confidence);}}

  if(raw.operationIds.some(x=>x===null)||raw.tokensRemaining===undefined){const last=rows.at(-1)??metrics.extractionHeight*.58,footerTop=Math.min(metrics.extractionHeight*.82,last+pitch*.72),footerRect=extractionToSource({left:metrics.extractionWidth*.22,top:footerTop,width:metrics.extractionWidth*.72,height:metrics.extractionHeight-footerTop},metrics),rec=await w.recognize(canvas(src,footerRect),{tessedit_pageseg_mode:'6'},{tsv:true}),words=parse(rec.data.tsv),all=orderedText(words);retries++;footerRetries++;
    if(raw.tokensRemaining===undefined){const n=parseTokens(all);if(n!==undefined){raw.tokensRemaining=n;setConfidence(raw,'tokensRemaining',.96);metrics.diagnostic.tokenEvidence={rawText:all,value:n,confidence:.96};}else metrics.diagnostic.tokenEvidence={rawText:all,value:null,confidence:0};}
    const centers=metrics.diagnostic.extractionColumnCenters,buttonCenters=[(centers.core+centers.mid)/2,centers.mid,(centers.mid+centers.support)/2],spacing=Math.min(buttonCenters[1]!-buttonCenters[0]!,buttonCenters[2]!-buttonCenters[1]!),sx=metrics.diagnostic.sourceCrop.width/metrics.extractionWidth,tokenWords=words.filter(x=>ocrSimilarity(x.text,'TOKENS')>=.62||/^\d+$/.test(x.text)),tokenY=tokenWords.length?tokenWords.reduce((sum,x)=>sum+x.top+x.height/2,0)/tokenWords.length:footerRect.height*.88,buttonTop=Math.max(0,tokenY-footerRect.height*.34),buttonHeight=Math.min(footerRect.height-buttonTop,footerRect.height*.24),buttonWidth=spacing*sx*1.08,resolved:[string|null,string|null,string|null]=[null,null,null],cardTexts:string[]=[];for(let i=0;i<3;i++){const centerSource=metrics.diagnostic.sourceCrop.left+buttonCenters[i]!*sx,rect={left:centerSource-buttonWidth/2,top:footerRect.top+buttonTop,width:buttonWidth,height:buttonHeight},buttonRec=await w.recognize(canvas(src,rect),{tessedit_pageseg_mode:'6'},{tsv:true}),buttonWords=parse(buttonRec.data.tsv),buttonText=orderedText(buttonWords),match=matchActionText(buttonText);retries++;footerRetries++;cardTexts.push(buttonText);if(match&&match.score>=.58){resolved[i]=match.id;raw.operationIds[i]=match.id;setConfidence(raw,`operationIds.${i}`,match.score);}}metrics.diagnostic.actionEvidence={resolved,reason:resolved.every(Boolean)?'resolved-by-native-button-crops':'native-button-crops-partial',cardTexts};
  }
  const elapsedMs=performance.now()-started;
  const diagnostic=metrics.diagnostic as typeof metrics.diagnostic & {refinementEvidence:{attempted:boolean;emblemRetries:number;teamRetries:number;footerRetries:number;elapsedMs:number}};
  diagnostic.refinementEvidence={attempted:true,emblemRetries,teamRetries,footerRetries,elapsedMs};
  raw.warnings=(raw.warnings??[]).filter(warning=>{
    const action=/Action (\d)/.exec(warning);if(action){const i=Number(action[1])-1;return raw.operationIds[i]===null;}
    if(/Roll token count/i.test(warning))return raw.tokensRemaining===undefined;
    return true;
  });
  return{result:raw,elapsedMs,retries};
}

export async function refineUncertainEmblemStats(file:File,data:DataBundle,raw:RawScreenshotImport):Promise<RawScreenshotImport>{void file;void data;return raw;}
