import type { BoardLayoutId, DataBundle, QualityTier, Role, StatName, TraitName } from '../domain/types.js';
import { BOARD_LAYOUTS, LEGAL_STAT_POOLS } from '../domain/rules.js';
import { ACTION_CATALOG } from '../data/actionCatalog.js';
import type { RawScreenshotImport, ScreenshotFieldConfidence } from './screenshotImport.js';

const ROLES: readonly Role[]=['core','mid','support'];
const TRAITS: readonly TraitName[]=['Fractal','Friendly','Vampiric','Unique','Benevolent'];
const OCR_CDN='https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js';
const LOCALIZE_MAX=1100, EXTRACT_MAX=1440;
interface Word { text:string; confidence:number; left:number; top:number; width:number; height:number; lineKey:string; }
interface Pass { words:Word[]; elapsedMs:number; width:number; height:number; }
interface Worker { recognize(image:HTMLCanvasElement,options?:Record<string,unknown>,output?:Record<string,boolean>):Promise<{data:{tsv?:string}}>; }
interface Tess { createWorker(language?:string):Promise<Worker>; }
declare global { interface Window { Tesseract?:Tess; } }
export interface LocalScreenshotOcrMetrics { sourceWidth:number;sourceHeight:number;localizationWidth:number;localizationHeight:number;extractionWidth:number;extractionHeight:number;localizationMs:number;extractionMs:number;totalMs:number;croppedPixelFraction:number; }
export interface LocalScreenshotOcrOutput { result:RawScreenshotImport;metrics:LocalScreenshotOcrMetrics; }
let workerPromise:Promise<Worker>|undefined;
const ALIASES:Record<StatName,string[]>={'Creep Score':['CREEP SCORE','CREEP'],GPM:['GPM'],Deaths:['DEATHS'],'Tower Kills':['TOWER KILLS','TOWER'],Madstone:['MADSTONE COLLECTED','MADSTONE'],Kills:['KILLS'],'Teamfight Participation':['TEAMFIGHT PARTICIPATION','TEAMFIGHT'],'Tormentor Kills':['TORMENTOR KILLS','TORMENTOR'],'Roshan Kills':['ROSHAN KILLS','ROSHAN'],Stuns:['STUNS'],'Courier Kills':['COURIER KILLS','COURIER'],'First Blood':['FIRST BLOOD'],Runes:['RUNES GRABBED','RUNES'],Watchers:['WATCHERS'],'Wards Placed':['WARDS PLACED','WARDS'],'Smokes Used':['SMOKES USED','SMOKES'],'Camps Stacked':['CAMPS STACKED','CAMPS'],Lotuses:['LOTUSES']};
const norm=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,'');
function distance(a:string,b:string):number{const p=Array.from({length:b.length+1},(_,i)=>i),n=new Array<number>(b.length+1);for(let i=1;i<=a.length;i++){n[0]=i;for(let j=1;j<=b.length;j++)n[j]=Math.min(n[j-1]!+1,p[j]!+1,p[j-1]!+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=b.length;j++)p[j]=n[j]!;}return p[b.length]!;}
function sim(a:string,b:string):number{const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x.includes(y)||y.includes(x))return Math.min(x.length,y.length)/Math.max(x.length,y.length);return 1-distance(x,y)/Math.max(x.length,y.length);}
const cx=(w:Word)=>w.left+w.width/2,cy=(w:Word)=>w.top+w.height/2,text=(ws:readonly Word[])=>[...ws].sort((a,b)=>a.left-b.left).map(w=>w.text).join(' ');
function groups(ws:readonly Word[]):Map<string,Word[]>{const m=new Map<string,Word[]>();for(const w of ws){const r=m.get(w.lineKey)??[];r.push(w);m.set(w.lineKey,r);}return m;}
async function runtime():Promise<Tess>{if(window.Tesseract)return window.Tesseract;await new Promise<void>((ok,no)=>{const old=document.querySelector<HTMLScriptElement>('script[data-local-ocr]');if(old){old.addEventListener('load',()=>ok(),{once:true});old.addEventListener('error',()=>no(new Error('Local OCR failed to load.')),{once:true});return;}const s=document.createElement('script');s.src=OCR_CDN;s.async=true;s.dataset.localOcr='1';s.onload=()=>ok();s.onerror=()=>no(new Error('Local OCR failed to load.'));document.head.appendChild(s);});if(!window.Tesseract)throw new Error('Local OCR runtime is unavailable.');return window.Tesseract;}
async function getWorker():Promise<Worker>{workerPromise??=(async()=>{const T=await runtime();return await T.createWorker('eng');})();return await workerPromise;}
export async function warmLocalScreenshotOcr():Promise<void>{await getWorker();}
async function decode(file:File):Promise<HTMLImageElement>{if(!file.type.startsWith('image/'))throw new Error('Choose an image screenshot (PNG, JPEG, or WebP).');return await new Promise((ok,no)=>{const i=new Image(),u=URL.createObjectURL(file);i.onload=()=>{URL.revokeObjectURL(u);ok(i);};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error('The selected screenshot could not be decoded.'));};i.src=u;});}
function canvas(i:HTMLImageElement,max:number,c?:{left:number;top:number;width:number;height:number}):HTMLCanvasElement{const s=c??{left:0,top:0,width:i.naturalWidth,height:i.naturalHeight},k=Math.min(1,max/Math.max(s.width,s.height)),o=document.createElement('canvas');o.width=Math.max(1,Math.round(s.width*k));o.height=Math.max(1,Math.round(s.height*k));const x=o.getContext('2d');if(!x)throw new Error('Canvas image processing is unavailable.');x.drawImage(i,s.left,s.top,s.width,s.height,0,0,o.width,o.height);return o;}
function parse(tsv?:string):Word[]{if(!tsv)return[];const out:Word[]=[];for(const row of tsv.split(/\r?\n/).slice(1)){const c=row.split('\t');if(c.length<12||c[0]!=='5')continue;const t=c.slice(11).join('\t').trim();if(t)out.push({text:t,confidence:Number(c[10])||0,left:Number(c[6])||0,top:Number(c[7])||0,width:Number(c[8])||0,height:Number(c[9])||0,lineKey:`${c[1]}:${c[2]}:${c[3]}:${c[4]}`});}return out;}
async function run(w:Worker,c:HTMLCanvasElement):Promise<Pass>{const t=performance.now(),r=await w.recognize(c,{}, {tsv:true});return{words:parse(r.data.tsv),elapsedMs:performance.now()-t,width:c.width,height:c.height};}
function centers(ws:readonly Word[],width:number):Record<Role,number>{const f={} as Partial<Record<Role,number>>;for(const r of ROLES){const a=ws.filter(w=>sim(w.text,r.toUpperCase())>=.72).sort((x,y)=>y.confidence-x.confidence);if(a[0])f[r]=cx(a[0]);}return Object.keys(f).length===3?f as Record<Role,number>:{core:width/6,mid:width/2,support:width*5/6};}
function cropBox(p:Pass,sw:number,sh:number){const c=centers(p.words,p.width),d=Math.min(c.mid-c.core,c.support-c.mid),l=Math.max(0,c.core-d*.58),r=Math.min(p.width,c.support+d*.58),h=p.words.filter(w=>ROLES.some(x=>sim(w.text,x.toUpperCase())>=.72)),t=h.length?Math.max(0,Math.min(...h.map(w=>w.top))-Math.max(20,p.height*.05)):0,sx=sw/p.width,sy=sh/p.height;return{left:Math.floor(l*sx),top:Math.floor(t*sy),width:Math.ceil((r-l)*sx),height:Math.ceil(sh-t*sy)};}
function bands(ws:readonly Word[],width:number):Record<Role,{left:number;right:number}>{const c=centers(ws,width),a=(c.core+c.mid)/2,b=(c.mid+c.support)/2;return{core:{left:0,right:a},mid:{left:a,right:b},support:{left:b,right:width}};}
function tiers(ws:readonly Word[],b:{left:number;right:number}):number[]{const ys=ws.filter(w=>cx(w)>=b.left&&cx(w)<b.right&&sim(w.text,'TIER')>=.65).map(cy).sort((a,z)=>a-z),g:number[]=[];for(const y of ys){if(!g.length||Math.abs(y-g.at(-1)!)>14)g.push(y);else g[g.length-1]=(g.at(-1)!+y)/2;}return g;}
function layoutOf(r:Record<Role,number[]>):BoardLayoutId{const n=ROLES.map(x=>r[x].length);if(n.filter(x=>x>=5).length>=2)return'expanded_5';if(n.filter(x=>x>=3).length>=2)return'legacy_3';return Math.max(...n)>=5?'expanded_5':'legacy_3';}
const within=(ws:readonly Word[],l:number,r:number,t:number,b:number)=>ws.filter(w=>cx(w)>=l&&cx(w)<r&&cy(w)>=t&&cy(w)<b);
function statMatch(s:string,legal:readonly StatName[]){let best={value:legal[0]!,score:-1};for(const v of legal){const score=Math.max(...ALIASES[v].map(a=>sim(s,a)));if(score>best.score)best={value:v,score};}return best;}
function traitMatch(s:string){let best={value:TRAITS[0]!,score:-1};for(const v of TRAITS){const score=sim(s,v);if(score>best.score)best={value:v,score};}return best;}
function tierMatch(s:string):{value:QualityTier;score:number}{const m=s.toUpperCase().match(/\b(?:III|IV|II|V|I)\b/g)??[],v=m.find(x=>x!=='I')??m[0],map:Record<string,QualityTier>={I:1,II:2,III:3,IV:4,V:5};return v&&map[v]?{value:map[v]!,score:.96}:{value:1,score:.2};}
function conf(score:number,ws:readonly Word[]):number{const o=ws.length?ws.reduce((s,w)=>s+w.confidence,0)/ws.length/100:0;return Math.max(0,Math.min(.99,score*.72+o*.28));}
function teamMatch(ws:readonly Word[],role:Role,data:DataBundle){const s=text(ws);let best={team:data.players.find(p=>p.role===role)?.team??'',score:-1};for(const p of data.players.filter(x=>x.role===role)){const q=[p.name,...p.attachedPlayers].map(n=>sim(s,n)),strong=q.filter(x=>x>.62),score=strong.length?Math.min(.99,strong.reduce((a,b)=>a+b,0)/Math.min(2,strong.length)):Math.max(...q,0);if(score>best.score)best={team:p.team,score};}return best;}
function rowWindow(rows:number[],i:number,height:number){const y=rows[i]??height*(.18+i*.14),prev=i?rows[i-1]!:Math.max(0,y-55),next=i<rows.length-1?rows[i+1]!:Math.min(height,y+65);return{top:i?(prev+y)/2:Math.max(0,y-(next-y)*.55),bottom:i<rows.length-1?(y+next)/2:Math.min(height,y+(y-prev)*.65)};}
export async function parseScreenshotLocally(file:File,data:DataBundle):Promise<LocalScreenshotOcrOutput>{const start=performance.now(),img=await decode(file),worker=await getWorker(),lc=canvas(img,LOCALIZE_MAX),local=await run(worker,lc),crop=cropBox(local,img.naturalWidth,img.naturalHeight),ec=canvas(img,EXTRACT_MAX,crop),ex=await run(worker,ec),bs=bands(ex.words,ex.width),rows=Object.fromEntries(ROLES.map(r=>[r,tiers(ex.words,bs[r])])) as Record<Role,number[]>,layoutId=layoutOf(rows),layout=BOARD_LAYOUTS[layoutId],fc:ScreenshotFieldConfidence[]=[],warnings:string[]=[],banners={} as RawScreenshotImport['banners'];for(const role of ROLES){const b=bs[role],rs=rows[role],first=rs[0]??ex.height*.2,tw=within(ex.words,b.left,b.left+(b.right-b.left)*.58,0,Math.max(first-5,ex.height*.24)),tm=teamMatch(tw,role,data);fc.push({path:`banners.${role}.selectedTeam`,confidence:tm.score});if(tm.score<.9)warnings.push(`${role} team OCR should be reviewed.`);const emblems=layout.roles[role].map((slot,i)=>{const rw=rowWindow(rs,i,ex.height),ww=within(ex.words,b.left+(b.right-b.left)*.46,b.right,rw.top,rw.bottom),s=text(ww),sm=statMatch(s,LEGAL_STAT_POOLS[slot.color]),tr=traitMatch(s),qt=tierMatch(s),sc=conf(sm.score,ww),tc=conf(tr.score,ww);fc.push({path:`banners.${role}.emblems.${i}.stat`,confidence:sc},{path:`banners.${role}.emblems.${i}.qualityTier`,confidence:qt.score},{path:`banners.${role}.emblems.${i}.trait`,confidence:tc});if(Math.min(sc,qt.score,tc)<.9)warnings.push(`${role} emblem ${i+1} OCR should be reviewed.`);return{position:slot.index,color:slot.color,stat:sm.value,qualityTier:qt.value,trait:tr.value};});banners[role]={selectedTeam:tm.team,emblems};}const last=Math.max(...ROLES.flatMap(r=>rows[r]),0),lines=[...groups(ex.words.filter(w=>cy(w)>last+25)).values()].map(text),ops:[string|null,string|null,string|null]=[null,null,null],used=new Set<string>();let oi=0;for(const line of lines){if(oi>=3)break;const m=ACTION_CATALOG.map(a=>({id:a.id,score:sim(line,a.label)})).sort((a,b)=>b.score-a.score)[0];if(m&&m.score>=.62&&!used.has(m.id)){ops[oi]=m.id;used.add(m.id);fc.push({path:`operationIds.${oi}`,confidence:m.score});oi++;}}while(oi<3){fc.push({path:`operationIds.${oi}`,confidence:0});warnings.push(`Action ${oi+1} is missing or unreadable.`);oi++;}return{result:{layoutId,banners,operationIds:ops,fieldConfidence:fc,warnings},metrics:{sourceWidth:img.naturalWidth,sourceHeight:img.naturalHeight,localizationWidth:local.width,localizationHeight:local.height,extractionWidth:ex.width,extractionHeight:ex.height,localizationMs:local.elapsedMs,extractionMs:ex.elapsedMs,totalMs:performance.now()-start,croppedPixelFraction:(crop.width*crop.height)/(img.naturalWidth*img.naturalHeight)}};}
