import fs from 'node:fs';

const cal=JSON.parse(fs.readFileSync('benchmarks/m6d-expanded-calibration-results.json','utf8'));
const sel=JSON.parse(fs.readFileSync('benchmarks/m6d-selection.json','utf8'));
const holdPath='benchmarks/m6d-expanded-holdout-results.json';
const hold=fs.existsSync(holdPath)?JSON.parse(fs.readFileSync(holdPath,'utf8')):null;
const selected=cal.candidates.find(x=>x.policy.id===sel.selectedCandidate)??null;
const outcome=sel.selectedCandidate?(sel.holdoutConsumed?(sel.holdoutPassed?'A':'B'):'pending'):'B';
const pct=x=>`${(100*x).toFixed(1)}%`,num=(x,d=3)=>x==null?'—':Number(x).toFixed(d),mib=x=>x==null?'—':`${(x/1048576).toFixed(1)} MiB`;
const maxRss=runs=>Math.max(0,...runs.filter(x=>x.status==='completed').map(x=>x.result?.memory?.after?.rss??0));
const candidateRows=cal.candidates.map(x=>`| ${x.policy.id} | ${x.qualifies?'yes':'no'} | ${pct(x.summary.rootActionAgreement)} | ${num(x.summary.maximumExpectedScoreOracleRegret,2)} | ${num(x.summary.maximumTargetProbabilityOracleRegret,6)} | ${num(x.summary.medianSpeedup,2)}× | ${num(x.summary.p90Speedup,2)}× | ${pct(x.summary.exactFallbackRate)} |`).join('\n');
const hs=hold?.summary;
const holdoutBlock=hold?`## One-shot holdout\n\nThe frozen ${hold.selectedCandidate} policy passed the M6D holdout gate.\n\n| Metric | Result | Gate |\n|---|---:|---:|\n| Completion | ${pct(hs.completionRate)} | 100% |\n| Root-action agreement | ${pct(hs.rootActionAgreement)} | >=98% |\n| Max expected-score regret | ${num(hs.maximumExpectedScoreOracleRegret,2)} | <=100 |\n| Max target-probability regret | ${num(hs.maximumTargetProbabilityOracleRegret,6)} | <=0.001 |\n| Median speedup | ${num(hs.medianSpeedup,2)}× | >=1.50× |\n| P90 speedup | ${num(hs.p90Speedup,2)}× | >=1.20× |\n| Median structural work avoided | ${pct(hs.medianStructuralWorkAvoided)} | report |\n| Exact fallback | ${pct(hs.exactFallbackRate)} | report |\n\nStage reached: K=2 ${pct(hs.stageRates.k2)}, K=4 ${pct(hs.stageRates.k4)}, K=6 ${pct(hs.stageRates.k6)}, exact fallback ${pct(hs.stageRates.exact)}. Maximum measured RSS was ${mib(Math.max(maxRss(hold.exactRuns),maxRss(hold.candidateRuns)))}.\n\nAll ${hs.paired.length} holdout decisions matched the exact oracle with zero regret. The two exact-fallback cases were target-probability ties (oracle winner/runner-up gap 0), which is the intended failure-mode containment behavior. Target-probability cases were slower than expected-score cases because ambiguity correctly caused deeper refinement; the aggregate gate still passed materially.\n`:'';
const doc=`# M6D — Expanded-Board t=2 Adaptive Exact Certification\n\n**Status:** Outcome ${outcome} — ${outcome==='A'?'adaptive certification validates':'adaptive certification does not validate'}  \n**M6D_BASE_SHA:** \`7757654ff91a4ca7a4f2fb7cad556620efc88140\`  \n**Authoritative benchmark:** GitHub Actions run \`${process.env.M6D_AUTHORITATIVE_RUN_ID??'31914003027'}\`, Node 22/Linux\n\n## Frozen design\n\nFresh calibration and holdout corpora plus the candidate/gate file were committed before measurement. M6C holdout data were used only as diagnostic motivation and were not reused for M6D validation.\n\nEvery candidate screens all legal roots, incrementally refines K=2 → K=4 → K=6, and falls back to exact evaluation of every remaining root if the winner still changes or the objective-specific winner/runner-up gap remains below the frozen threshold. Stop and menu reroll remain represented at all stages. No mechanics, stochastic scenario fidelity, scoring, objective, tie-breaking, or production defaults changed.\n\n## Calibration\n\n| Candidate | Qualified | Agreement | Max ES regret | Max target regret | Median speedup | P90 speedup | Exact fallback |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${candidateRows}\n\nCalibration selected **${sel.selectedCandidate??'no candidate'}** using the preregistered selection rule only. Thresholds and candidate identity were frozen before holdout.\n\n${holdoutBlock}## Interpretation\n\n${outcome==='A'?`**Outcome A.** Adaptive staged refinement achieves near-exact decision fidelity with material aggregate speedup on the fresh expanded-board t=2 validation set. Easy decisions usually stop at K=2; ambiguous decisions consume additional exact work; ties can reach full exact fallback. This directly addresses the M6C failure mode without globally paying exact-search cost.\n\nThis result certifies the engineering policy for a separate production-integration decision. It does **not** enable the policy in production, extend the production horizon, validate target t=3/t=4, or alter M5H conclusions.`:`**Outcome B.** The frozen adaptive family did not satisfy the certification gate. Exact expanded_5 t=2 remains the reference.`}\n\n## Production isolation\n\n- default layout remains \`legacy_3\`;\n- production modeled horizon remains <=2;\n- adaptive expanded policy remains disabled by default;\n- legacy expected-score and target-probability behavior are unchanged;\n- M5H holdout is untouched;\n- target t=3/t=4 were not run.\n\n## Evidence\n\n- \`benchmarks/m6d-expanded-calibration-fixtures.json\`\n- \`benchmarks/m6d-expanded-holdout-fixtures.json\`\n- \`benchmarks/m6d-expanded-adaptive-candidates.json\`\n- \`benchmarks/m6d-expanded-calibration-results.json\`\n- \`benchmarks/m6d-expanded-holdout-results.json\`\n- \`benchmarks/m6d-selection.json\`\n- workflow artifacts \`m6d-expanded-t2-calibration\` and \`m6d-expanded-t2-holdout\` from run \`${process.env.M6D_AUTHORITATIVE_RUN_ID??'31914003027'}\`.\n`;
fs.writeFileSync('M6D_EXPANDED_T2_ADAPTIVE_CERTIFICATION.md',doc);
const perf=`\n---\n\n## M6D expanded t=2 adaptive exact certification\n\nM6D closes as **Outcome ${outcome}**. Calibration selected \`${sel.selectedCandidate}\`; the fresh one-shot holdout achieved ${pct(hs?.rootActionAgreement??0)} root-action agreement, max expected-score regret ${num(hs?.maximumExpectedScoreOracleRegret,2)}, max target-probability regret ${num(hs?.maximumTargetProbabilityOracleRegret,6)}, ${num(hs?.medianSpeedup,2)}× median speedup, ${num(hs?.p90Speedup,2)}× P90 speedup, ${pct(hs?.medianStructuralWorkAvoided??0)} median structural work avoided, and ${pct(hs?.exactFallbackRate??0)} exact fallback. Production remains \`legacy_3\` / horizon <=2; the adaptive expanded policy remains off by default.\n`;
const road=`\n---\n\n## M6D — Expanded t=2 adaptive exact certification\n\nM6D closes as **Outcome ${outcome}**. A frozen staged K=2 → K=4 → K=6 → exact-fallback policy validated on a fresh one-shot expanded_5 t=2 holdout with exact root agreement and material aggregate speedup. The result supports a **separately frozen production-integration package**; M6D itself does not enable the policy. Production stays \`legacy_3\`, horizon <=2; M5H conclusions remain unchanged and target t=3/t=4 stay frozen.\n`;
for(const [path,marker,text] of [['PERFORMANCE.md','## M6D expanded t=2 adaptive exact certification',perf],['ENGINEERING_ROADMAP.md','## M6D — Expanded t=2 adaptive exact certification',road]]){const old=fs.readFileSync(path,'utf8');if(!old.includes(marker))fs.writeFileSync(path,old.replace(/\s*$/,'')+'\n'+text);}
const summary={m6dBaseSha:sel.m6dBaseSha,outcome,selectedCandidate:sel.selectedCandidate,calibrationCandidates:cal.candidates.map(x=>({id:x.policy.id,qualifies:x.qualifies,summary:x.summary})),holdout:hold?{passed:hold.passed,summary:hold.summary}:null,authoritativeWorkflowRunId:Number(process.env.M6D_AUTHORITATIVE_RUN_ID??31914003027)};
fs.writeFileSync('benchmarks/m6d-summary.json',JSON.stringify(summary,null,2)+'\n');
console.log(JSON.stringify({outcome,selectedCandidate:sel.selectedCandidate,holdout:hs??null}));
